version: 1.0

#MongoDB section *˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜
mongodb:
  url: mongodb+srv://teste:t3st3s321@backendtj.6vftg.mongodb.net/BackendTJ?retryWrites=true&w=majority
  db: BackendTJ
  #url: mongodb+srv://p1p0c4d0c3:p1p0c4d0c3@cluster0.o8okt.mongodb.net/magazineTj?retryWrites=true&w=majority
  #db: magazineTj


#Looging section *˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜*˜
disable_existing_loggers: true

formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'


handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: INFO
    formatter: simple
    filename: client.log

loggers:
  client:
    level: INFO
    handlers: [console,file]
    propagate: no

root:
  level: INFO
  handlers: [console]
